[tool.poetry]
name = "2-lab"
version = "0.1.0"
description = ""
authors = ["bbuhyl <bbuhyl@cisco.com>"]
readme = "README.readme"

[tool.poetry.dependencies]
python = "^3.12"
mypy = "^1.14.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
