# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# name: Send Coverage Report

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# permissions:
#   contents: read

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python 3.12
#       uses: actions/setup-python@v3
#       with:
#         python-version: "3.12"
#     - name: Setup Poetry
#       uses: Gr1N/setup-poetry@v9
#     - name: Install dependency
#       working-directory: ./testing/2_lab
#       run: |
#         poetry install --no-root
#     - name: Test with pytest
#       working-directory: ./testing/2_lab
#       run: |
#         poetry run coverage run -m pytest
#         poetry run coverage xml
#     - name: Generate Coverage report
#       if: always()
#       working-directory: ./testing/2_lab
#       run: |
#         poetry run coverage xml  
#         poetry run pytest --cov --junitxml=junit.xml -o junit_family=legacy
#     - name: Upload test results to Codecov
#       if: ${{ !cancelled() }}
#       uses: codecov/test-results-action@v1
#       with:
#         directory: ./testing/2_lab
#         token: ${{ secrets.CODECOV_TOKEN }}
#     - name: Upload coverage reports to Codecov
#       uses: codecov/codecov-action@v5
#       if: always()
#       with:
#         directory: ./testing/2_lab
#         token: ${{ secrets.CODECOV_TOKEN }}